# Run from the source root (needs ffx_a.h and ffx_fsr1.h from github.com/GPUOpen-Effects/FidelityFX-FSR in ~/src/fsr).
# Generates engines/scumm/remaster_fsr.inc: AMD FidelityFX Super Resolution 1 (EASU + RCAS, MIT licence) as
# GLSL compute shaders over plain buffers, for the remaster renderer's "fsr" upscaler.
import os
src = os.path.expanduser("~/src/fsr")
a = open(os.path.join(src, "ffx_a.h")).read()
f = open(os.path.join(src, "ffx_fsr1.h")).read()
assert ")FSR\"" not in a + f

easu = r'''#version 450
layout(binding = 0) readonly buffer src_blob { uint src_data[]; };
layout(binding = 1) writeonly buffer dst_blob { uint dst_data[]; };
layout(push_constant) uniform parameter { uint c0; uint c1; uint c2; uint c3; uint c4; uint c5; uint c6; uint c7; uint c8; uint c9; uint c10; uint c11; uint c12; uint c13; uint c14; uint c15; int iw; int ih; int ow; int oh; } p;
#define A_GPU 1
#define A_GLSL 1
''' + a + r'''
vec3 fsrTexel(int x, int y) {
	x = clamp(x, 0, p.iw - 1);
	y = clamp(y, 0, p.ih - 1);
	return unpackUnorm4x8(src_data[y * p.iw + x]).rgb;
}
// textureGather(p) order: (i, j+1), (i+1, j+1), (i+1, j), (i, j) of the 2x2 texels around p
ivec2 fsrQuad(vec2 q) { return ivec2(floor(q * vec2(p.iw, p.ih) - 0.5)); }
AF4 FsrEasuRF(AF2 q) { ivec2 i = fsrQuad(q); return vec4(fsrTexel(i.x, i.y + 1).r, fsrTexel(i.x + 1, i.y + 1).r, fsrTexel(i.x + 1, i.y).r, fsrTexel(i.x, i.y).r); }
AF4 FsrEasuGF(AF2 q) { ivec2 i = fsrQuad(q); return vec4(fsrTexel(i.x, i.y + 1).g, fsrTexel(i.x + 1, i.y + 1).g, fsrTexel(i.x + 1, i.y).g, fsrTexel(i.x, i.y).g); }
AF4 FsrEasuBF(AF2 q) { ivec2 i = fsrQuad(q); return vec4(fsrTexel(i.x, i.y + 1).b, fsrTexel(i.x + 1, i.y + 1).b, fsrTexel(i.x + 1, i.y).b, fsrTexel(i.x, i.y).b); }
#define FSR_EASU_F 1
''' + f + r'''
void main() {
	const ivec2 o = ivec2(gl_GlobalInvocationID.xy);
	if (o.x >= p.ow || o.y >= p.oh)
		return;
	AF3 c;
	FsrEasuF(c, AU2(o), uvec4(p.c0, p.c1, p.c2, p.c3), uvec4(p.c4, p.c5, p.c6, p.c7), uvec4(p.c8, p.c9, p.c10, p.c11),
	         uvec4(p.c12, p.c13, p.c14, p.c15));
	dst_data[o.y * p.ow + o.x] = packUnorm4x8(vec4(clamp(c, 0.0, 1.0), 1.0));
}
'''

rcas = r'''#version 450
layout(binding = 0) readonly buffer src_blob { uint src_data[]; };
layout(binding = 1) writeonly buffer dst_blob { uint dst_data[]; };
layout(push_constant) uniform parameter { uint c0; uint c1; uint c2; uint c3; int ow; int oh; } p;
#define A_GPU 1
#define A_GLSL 1
''' + a + r'''
AF4 FsrRcasLoadF(ASU2 q) {
	q = clamp(q, ivec2(0), ivec2(p.ow - 1, p.oh - 1));
	return unpackUnorm4x8(src_data[q.y * p.ow + q.x]);
}
void FsrRcasInputF(inout AF1 r, inout AF1 g, inout AF1 b) {}
#define FSR_RCAS_F 1
''' + f + r'''
void main() {
	const ivec2 o = ivec2(gl_GlobalInvocationID.xy);
	if (o.x >= p.ow || o.y >= p.oh)
		return;
	AF1 r, g, b;
	FsrRcasF(r, g, b, AU2(o), uvec4(p.c0, p.c1, p.c2, p.c3));
	dst_data[o.y * p.ow + o.x] = packUnorm4x8(vec4(clamp(vec3(r, g, b), 0.0, 1.0), 1.0));
}
'''

out = "// Generated by dists/remaster/fsr_gen.py from AMD FidelityFX Super Resolution 1 (ffx_a.h, ffx_fsr1.h).\n"
out += "// Copyright (c) 2021 Advanced Micro Devices, Inc. MIT licence, see dists/remaster/licenses/FidelityFX-FSR.txt.\n\n"
out += "static const char kFsrEasuShader[] = R\"FSR(" + easu + ")FSR\";\n\n"
out += "static const char kFsrRcasShader[] = R\"FSR(" + rcas + ")FSR\";\n"
open("engines/scumm/remaster_fsr.inc", "w").write(out)
os.makedirs("dists/remaster/licenses", exist_ok=True)
open("dists/remaster/licenses/FidelityFX-FSR.txt", "w").write(open(os.path.join(src, "LICENSE.txt")).read())
print("generated", len(out))
